import type { RigPreset } from './types';

/**
 * Canonical VRM humanoid bone names — duplicated here so presets are self-contained.
 * See https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0/humanoid.md
 */
export const VRM_BONE_NAMES = new Set([
  'hips', 'spine', 'chest', 'upperChest', 'neck', 'head',
  'leftEye', 'rightEye', 'jaw',
  'leftShoulder', 'leftUpperArm', 'leftLowerArm', 'leftHand',
  'rightShoulder', 'rightUpperArm', 'rightLowerArm', 'rightHand',
  'leftUpperLeg', 'leftLowerLeg', 'leftFoot', 'leftToes',
  'rightUpperLeg', 'rightLowerLeg', 'rightFoot', 'rightToes',
  'leftThumbMetacarpal', 'leftThumbProximal', 'leftThumbDistal',
  'leftIndexProximal', 'leftIndexIntermediate', 'leftIndexDistal',
  'leftMiddleProximal', 'leftMiddleIntermediate', 'leftMiddleDistal',
  'leftRingProximal', 'leftRingIntermediate', 'leftRingDistal',
  'leftLittleProximal', 'leftLittleIntermediate', 'leftLittleDistal',
  'rightThumbMetacarpal', 'rightThumbProximal', 'rightThumbDistal',
  'rightIndexProximal', 'rightIndexIntermediate', 'rightIndexDistal',
  'rightMiddleProximal', 'rightMiddleIntermediate', 'rightMiddleDistal',
  'rightRingProximal', 'rightRingIntermediate', 'rightRingDistal',
  'rightLittleProximal', 'rightLittleIntermediate', 'rightLittleDistal',
]);

const MIXAMO_BONE_MAP: Record<string, string> = {
  Hips: 'hips',
  Spine: 'spine',
  Spine1: 'chest',
  Spine2: 'upperChest',
  Neck: 'neck',
  Head: 'head',
  LeftShoulder: 'leftShoulder',
  LeftArm: 'leftUpperArm',
  LeftForeArm: 'leftLowerArm',
  LeftHand: 'leftHand',
  RightShoulder: 'rightShoulder',
  RightArm: 'rightUpperArm',
  RightForeArm: 'rightLowerArm',
  RightHand: 'rightHand',
  LeftUpLeg: 'leftUpperLeg',
  LeftLeg: 'leftLowerLeg',
  LeftFoot: 'leftFoot',
  LeftToeBase: 'leftToes',
  RightUpLeg: 'rightUpperLeg',
  RightLeg: 'rightLowerLeg',
  RightFoot: 'rightFoot',
  RightToeBase: 'rightToes',
  LeftHandThumb1: 'leftThumbMetacarpal',
  LeftHandThumb2: 'leftThumbProximal',
  LeftHandThumb3: 'leftThumbDistal',
  LeftHandIndex1: 'leftIndexProximal',
  LeftHandIndex2: 'leftIndexIntermediate',
  LeftHandIndex3: 'leftIndexDistal',
  LeftHandMiddle1: 'leftMiddleProximal',
  LeftHandMiddle2: 'leftMiddleIntermediate',
  LeftHandMiddle3: 'leftMiddleDistal',
  LeftHandRing1: 'leftRingProximal',
  LeftHandRing2: 'leftRingIntermediate',
  LeftHandRing3: 'leftRingDistal',
  LeftHandPinky1: 'leftLittleProximal',
  LeftHandPinky2: 'leftLittleIntermediate',
  LeftHandPinky3: 'leftLittleDistal',
  RightHandThumb1: 'rightThumbMetacarpal',
  RightHandThumb2: 'rightThumbProximal',
  RightHandThumb3: 'rightThumbDistal',
  RightHandIndex1: 'rightIndexProximal',
  RightHandIndex2: 'rightIndexIntermediate',
  RightHandIndex3: 'rightIndexDistal',
  RightHandMiddle1: 'rightMiddleProximal',
  RightHandMiddle2: 'rightMiddleIntermediate',
  RightHandMiddle3: 'rightMiddleDistal',
  RightHandRing1: 'rightRingProximal',
  RightHandRing2: 'rightRingIntermediate',
  RightHandRing3: 'rightRingDistal',
  RightHandPinky1: 'rightLittleProximal',
  RightHandPinky2: 'rightLittleIntermediate',
  RightHandPinky3: 'rightLittleDistal',
};

export const mixamoPreset: RigPreset = {
  id: 'mixamo',
  displayName: 'Mixamo (Adobe)',
  upAxis: 'y',
  prefixStrip: [/^mixamorig1?/],
  boneMap: MIXAMO_BONE_MAP,
  hipsNodeNames: ['mixamorigHips', 'mixamorig1Hips', 'Hips'],
  rootMotionMode: 'inPlace',
  detect: {
    trackPatterns: [/^mixamorig1?/i],
  },
  description: 'Adobe Mixamo / Fuse — Y-up, T-pose, mixamorig* prefix.',
};

const UE5_BONE_MAP: Record<string, string> = {
  pelvis: 'hips',
  spine_01: 'spine',
  spine_02: 'chest',
  spine_03: 'upperChest',
  // spine_04 / spine_05 are merged conceptually — kernel will drop unmapped tracks
  neck_01: 'neck',
  head: 'head',
  clavicle_l: 'leftShoulder',
  upperarm_l: 'leftUpperArm',
  lowerarm_l: 'leftLowerArm',
  hand_l: 'leftHand',
  clavicle_r: 'rightShoulder',
  upperarm_r: 'rightUpperArm',
  lowerarm_r: 'rightLowerArm',
  hand_r: 'rightHand',
  thigh_l: 'leftUpperLeg',
  calf_l: 'leftLowerLeg',
  foot_l: 'leftFoot',
  ball_l: 'leftToes',
  thigh_r: 'rightUpperLeg',
  calf_r: 'rightLowerLeg',
  foot_r: 'rightFoot',
  ball_r: 'rightToes',
  thumb_01_l: 'leftThumbMetacarpal',
  thumb_02_l: 'leftThumbProximal',
  thumb_03_l: 'leftThumbDistal',
  index_01_l: 'leftIndexProximal',
  index_02_l: 'leftIndexIntermediate',
  index_03_l: 'leftIndexDistal',
  middle_01_l: 'leftMiddleProximal',
  middle_02_l: 'leftMiddleIntermediate',
  middle_03_l: 'leftMiddleDistal',
  ring_01_l: 'leftRingProximal',
  ring_02_l: 'leftRingIntermediate',
  ring_03_l: 'leftRingDistal',
  pinky_01_l: 'leftLittleProximal',
  pinky_02_l: 'leftLittleIntermediate',
  pinky_03_l: 'leftLittleDistal',
  thumb_01_r: 'rightThumbMetacarpal',
  thumb_02_r: 'rightThumbProximal',
  thumb_03_r: 'rightThumbDistal',
  index_01_r: 'rightIndexProximal',
  index_02_r: 'rightIndexIntermediate',
  index_03_r: 'rightIndexDistal',
  middle_01_r: 'rightMiddleProximal',
  middle_02_r: 'rightMiddleIntermediate',
  middle_03_r: 'rightMiddleDistal',
  ring_01_r: 'rightRingProximal',
  ring_02_r: 'rightRingIntermediate',
  ring_03_r: 'rightRingDistal',
  pinky_01_r: 'rightLittleProximal',
  pinky_02_r: 'rightLittleIntermediate',
  pinky_03_r: 'rightLittleDistal',
};

export const ue5Preset: RigPreset = {
  id: 'ue5_manny',
  displayName: 'Unreal Engine 5 (Manny / Quinn)',
  upAxis: 'z',
  prefixStrip: [],
  boneMap: UE5_BONE_MAP,
  hipsNodeNames: ['pelvis', 'root'],
  rootMotionMode: 'inPlace',
  detect: {
    trackPatterns: [/^pelvis\./, /^spine_0[123]\./, /^clavicle_[lr]\./, /^thigh_[lr]\./],
    objectNames: ['pelvis', 'spine_01', 'thigh_l'],
  },
  description: 'UE5 default humanoid (Manny/Quinn/MetaHuman). Z-up FBX, 5-segment spine.',
};

const UNITY_HUMANOID_MAP: Record<string, string> = {
  Hips: 'hips',
  Spine: 'spine',
  Chest: 'chest',
  UpperChest: 'upperChest',
  Neck: 'neck',
  Head: 'head',
  LeftShoulder: 'leftShoulder',
  LeftUpperArm: 'leftUpperArm',
  LeftLowerArm: 'leftLowerArm',
  LeftHand: 'leftHand',
  RightShoulder: 'rightShoulder',
  RightUpperArm: 'rightUpperArm',
  RightLowerArm: 'rightLowerArm',
  RightHand: 'rightHand',
  LeftUpperLeg: 'leftUpperLeg',
  LeftLowerLeg: 'leftLowerLeg',
  LeftFoot: 'leftFoot',
  LeftToes: 'leftToes',
  RightUpperLeg: 'rightUpperLeg',
  RightLowerLeg: 'rightLowerLeg',
  RightFoot: 'rightFoot',
  RightToes: 'rightToes',
  LeftThumbProximal: 'leftThumbMetacarpal',
  LeftThumbIntermediate: 'leftThumbProximal',
  LeftThumbDistal: 'leftThumbDistal',
  LeftIndexProximal: 'leftIndexProximal',
  LeftIndexIntermediate: 'leftIndexIntermediate',
  LeftIndexDistal: 'leftIndexDistal',
  LeftMiddleProximal: 'leftMiddleProximal',
  LeftMiddleIntermediate: 'leftMiddleIntermediate',
  LeftMiddleDistal: 'leftMiddleDistal',
  LeftRingProximal: 'leftRingProximal',
  LeftRingIntermediate: 'leftRingIntermediate',
  LeftRingDistal: 'leftRingDistal',
  LeftLittleProximal: 'leftLittleProximal',
  LeftLittleIntermediate: 'leftLittleIntermediate',
  LeftLittleDistal: 'leftLittleDistal',
  RightThumbProximal: 'rightThumbMetacarpal',
  RightThumbIntermediate: 'rightThumbProximal',
  RightThumbDistal: 'rightThumbDistal',
  RightIndexProximal: 'rightIndexProximal',
  RightIndexIntermediate: 'rightIndexIntermediate',
  RightIndexDistal: 'rightIndexDistal',
  RightMiddleProximal: 'rightMiddleProximal',
  RightMiddleIntermediate: 'rightMiddleIntermediate',
  RightMiddleDistal: 'rightMiddleDistal',
  RightRingProximal: 'rightRingProximal',
  RightRingIntermediate: 'rightRingIntermediate',
  RightRingDistal: 'rightRingDistal',
  RightLittleProximal: 'rightLittleProximal',
  RightLittleIntermediate: 'rightLittleIntermediate',
  RightLittleDistal: 'rightLittleDistal',
};

export const unityHumanoidPreset: RigPreset = {
  id: 'unity_humanoid',
  displayName: 'Unity Mecanim Humanoid',
  upAxis: 'y',
  prefixStrip: [/^Armature\|/],
  boneMap: UNITY_HUMANOID_MAP,
  hipsNodeNames: ['Hips', 'Armature|Hips'],
  rootMotionMode: 'inPlace',
  isHandednessMirrored: true, // Unity is left-handed; FBX export usually keeps this
  detect: {
    objectNames: ['LeftUpperArm', 'RightUpperArm', 'UpperChest'],
  },
  description: 'Unity Mecanim humanoid skeleton — names are PascalCase humanoid.',
};

const BVH_STANDARD_MAP: Record<string, string> = {
  Hips: 'hips',
  Spine: 'spine',
  Spine1: 'chest',
  Spine2: 'upperChest',
  Neck: 'neck',
  Head: 'head',
  LeftShoulder: 'leftShoulder',
  LeftArm: 'leftUpperArm',
  LeftForeArm: 'leftLowerArm',
  LeftHand: 'leftHand',
  RightShoulder: 'rightShoulder',
  RightArm: 'rightUpperArm',
  RightForeArm: 'rightLowerArm',
  RightHand: 'rightHand',
  LeftUpLeg: 'leftUpperLeg',
  LeftLeg: 'leftLowerLeg',
  LeftFoot: 'leftFoot',
  LeftToeBase: 'leftToes',
  RightUpLeg: 'rightUpperLeg',
  RightLeg: 'rightLowerLeg',
  RightFoot: 'rightFoot',
  RightToeBase: 'rightToes',
  // 3ds Max biped fallback names
  Bip01_Pelvis: 'hips',
  Bip01_Spine: 'spine',
  Bip01_Spine1: 'chest',
  Bip01_Spine2: 'upperChest',
  Bip01_Neck: 'neck',
  Bip01_Head: 'head',
  Bip01_L_Clavicle: 'leftShoulder',
  Bip01_L_UpperArm: 'leftUpperArm',
  Bip01_L_Forearm: 'leftLowerArm',
  Bip01_L_Hand: 'leftHand',
  Bip01_R_Clavicle: 'rightShoulder',
  Bip01_R_UpperArm: 'rightUpperArm',
  Bip01_R_Forearm: 'rightLowerArm',
  Bip01_R_Hand: 'rightHand',
  Bip01_L_Thigh: 'leftUpperLeg',
  Bip01_L_Calf: 'leftLowerLeg',
  Bip01_L_Foot: 'leftFoot',
  Bip01_L_Toe0: 'leftToes',
  Bip01_R_Thigh: 'rightUpperLeg',
  Bip01_R_Calf: 'rightLowerLeg',
  Bip01_R_Foot: 'rightFoot',
  Bip01_R_Toe0: 'rightToes',
};

export const bvhStandardPreset: RigPreset = {
  id: 'bvh_standard',
  displayName: 'BVH (CMU / standard biped)',
  upAxis: 'y',
  prefixStrip: [/^Character1_/, /^character_/],
  boneMap: BVH_STANDARD_MAP,
  hipsNodeNames: ['Hips', 'Bip01_Pelvis', 'hip'],
  rootMotionMode: 'inPlace',
  detect: {
    objectNames: ['LeftUpLeg', 'RightUpLeg', 'Bip01_Pelvis'],
  },
  description: 'CMU Mocap / 3ds Max biped names. BVHLoader yields these.',
};

const VROID_MAP: Record<string, string> = {
  // VRoid Studio bone names are typically Japanese-ish PascalCase
  J_Bip_C_Hips: 'hips',
  J_Bip_C_Spine: 'spine',
  J_Bip_C_Chest: 'chest',
  J_Bip_C_UpperChest: 'upperChest',
  J_Bip_C_Neck: 'neck',
  J_Bip_C_Head: 'head',
  J_Bip_L_Shoulder: 'leftShoulder',
  J_Bip_L_UpperArm: 'leftUpperArm',
  J_Bip_L_LowerArm: 'leftLowerArm',
  J_Bip_L_Hand: 'leftHand',
  J_Bip_R_Shoulder: 'rightShoulder',
  J_Bip_R_UpperArm: 'rightUpperArm',
  J_Bip_R_LowerArm: 'rightLowerArm',
  J_Bip_R_Hand: 'rightHand',
  J_Bip_L_UpperLeg: 'leftUpperLeg',
  J_Bip_L_LowerLeg: 'leftLowerLeg',
  J_Bip_L_Foot: 'leftFoot',
  J_Bip_L_ToeBase: 'leftToes',
  J_Bip_R_UpperLeg: 'rightUpperLeg',
  J_Bip_R_LowerLeg: 'rightLowerLeg',
  J_Bip_R_Foot: 'rightFoot',
  J_Bip_R_ToeBase: 'rightToes',
};

export const vroidPreset: RigPreset = {
  id: 'vroid',
  displayName: 'VRoid Studio (J_Bip_*)',
  upAxis: 'y',
  prefixStrip: [],
  boneMap: VROID_MAP,
  hipsNodeNames: ['J_Bip_C_Hips'],
  rootMotionMode: 'inPlace',
  rotationMode: 'rest-offset',
  detect: {
    objectNames: ['J_Bip_C_Hips', 'J_Bip_L_UpperArm'],
    trackPatterns: [/^J_Bip_/],
  },
  description: 'VRoid Studio internal naming (J_Bip_*). Uses hierarchical rest-delta because local axes can differ across VRM exports.',
};

const SMPL_MAP: Record<string, string> = {
  pelvis: 'hips',
  spine1: 'spine',
  spine2: 'chest',
  spine3: 'upperChest',
  neck: 'neck',
  head: 'head',
  left_collar: 'leftShoulder',
  left_shoulder: 'leftUpperArm',
  left_elbow: 'leftLowerArm',
  left_wrist: 'leftHand',
  right_collar: 'rightShoulder',
  right_shoulder: 'rightUpperArm',
  right_elbow: 'rightLowerArm',
  right_wrist: 'rightHand',
  left_hip: 'leftUpperLeg',
  left_knee: 'leftLowerLeg',
  left_ankle: 'leftFoot',
  left_foot: 'leftToes',
  right_hip: 'rightUpperLeg',
  right_knee: 'rightLowerLeg',
  right_ankle: 'rightFoot',
  right_foot: 'rightToes',
};

export const smplPreset: RigPreset = {
  id: 'smpl',
  displayName: 'SMPL / SMPL-X (research mocap)',
  upAxis: 'y',
  prefixStrip: [/^body_/, /^smpl_/i],
  boneMap: SMPL_MAP,
  hipsNodeNames: ['pelvis'],
  rootMotionMode: 'inPlace',
  detect: {
    objectNames: ['pelvis', 'left_collar', 'right_wrist'],
    trackPatterns: [/^left_(hip|knee|ankle)\./, /^right_(hip|knee|ankle)\./, /^left_collar\./],
  },
  description: 'SMPL / SMPL-X body model (24 / 55 joints). Common for AI-generated motion.',
};

export const allPresets: RigPreset[] = [
  mixamoPreset,
  ue5Preset,
  unityHumanoidPreset,
  vroidPreset,
  bvhStandardPreset,
  smplPreset,
];

export const presetById = new Map(allPresets.map((p) => [p.id, p]));
