// Semantic motion library over all vrma packs (vroid / mate-engine / vmagicmirror / sing).
// Data file is generated by scripts/build-motion-library.mjs — regenerate after adding packs.
import { publicUrl } from '@/lib/publicUrl';
import { s3Asset } from '@/lib/s3Assets';
import type { AnimationItem } from '@/components/lab/domain/types';
import libraryJson from './motionLibrary.json';

export type MotionCategory =
  | 'idle'
  | 'greet'
  | 'talk'
  | 'think'
  | 'listen'
  | 'react_positive'
  | 'react_negative'
  | 'react_surprise'
  | 'success'
  | 'dance'
  | 'sing'
  | 'sleep'
  | 'stretch'
  | 'pose'
  | 'face'
  | 'locomotion'
  | 'combat'
  | 'studio'
  | 'system'
  | 'misc';

export type MotionPosture = 'stand' | 'sit' | 'lie' | 'crouch' | 'float' | 'any';

export type MotionClip = {
  id: string;
  pack: 'vroid' | 'mate-engine' | 'vmagicmirror' | 'sing' | 'oror';
  name: string;
  /** 相对 public/ 的路径；远程包为空串，改用 url。 */
  file: string;
  /** 远程包（S3 托管，按需下载）的完整 URL。 */
  url?: string;
  duration: number | null;
  category: MotionCategory;
  tags: string[];
  emotion: string;
  energy: 1 | 2 | 3;
  loop: boolean;
  /** Single-pose clip (no inter-frame motion) — hold with crossfade, not a gesture. */
  static: boolean;
  posture: MotionPosture;
  usable: boolean;
  desc_zh: string;
};

export const MOTION_CLIPS = libraryJson.clips as MotionClip[];
export const USABLE_MOTION_CLIPS = MOTION_CLIPS.filter((c) => c.usable);

const clipById = new Map<string, MotionClip>();
const clipByNormalizedName = new Map<string, MotionClip>();

function normalizeName(name: string) {
  const withoutPath = name.split(/[\\/]/).pop() ?? name;
  return withoutPath
    .replace(/\.(vrma|fbx|glb|gltf)$/i, '')
    .trim()
    .toLowerCase()
    .replace(/[\s-]+/g, '_');
}

for (const clip of MOTION_CLIPS) {
  clipById.set(clip.id, clip);
  const key = normalizeName(clip.name);
  if (!clipByNormalizedName.has(key)) clipByNormalizedName.set(key, clip);
}

export function findMotionClip(ref: string): MotionClip | null {
  return clipById.get(ref) ?? clipByNormalizedName.get(normalizeName(ref)) ?? null;
}

export type MotionQuery = Partial<{
  category: MotionCategory | MotionCategory[];
  posture: MotionPosture;
  emotion: string;
  tag: string;
  pack: MotionClip['pack'];
  loop: boolean;
  minEnergy: number;
  maxEnergy: number;
  maxDuration: number;
}>;

/** Query usable clips by semantic attributes. */
export function queryMotions(q: MotionQuery = {}): MotionClip[] {
  const categories = q.category ? (Array.isArray(q.category) ? q.category : [q.category]) : null;
  return USABLE_MOTION_CLIPS.filter((c) => {
    if (categories && !categories.includes(c.category)) return false;
    if (q.posture && c.posture !== q.posture && c.posture !== 'any') return false;
    if (q.emotion && c.emotion !== q.emotion) return false;
    if (q.tag && !c.tags.includes(q.tag)) return false;
    if (q.pack && c.pack !== q.pack) return false;
    if (q.loop !== undefined && c.loop !== q.loop) return false;
    if (q.minEnergy !== undefined && c.energy < q.minEnergy) return false;
    if (q.maxEnergy !== undefined && c.energy > q.maxEnergy) return false;
    if (q.maxDuration !== undefined && c.duration !== null && c.duration > q.maxDuration) return false;
    return true;
  });
}

export function motionClipToAnimationItem(clip: MotionClip): AnimationItem {
  const bundledMotionPrefix = 'assets/animation/';
  const url = clip.url ?? (clip.file.startsWith(bundledMotionPrefix)
    ? s3Asset(`animations/vrma/${clip.file.slice(bundledMotionPrefix.length)}`)
    : publicUrl(clip.file));
  return { id: clip.id, name: clip.name, url };
}

/** Every usable clip as an AnimationItem (all packs). */
export const MOTION_LIBRARY_ITEMS: AnimationItem[] = USABLE_MOTION_CLIPS.map(motionClipToAnimationItem);
